name: Build Images
on:
  push:
    branches:
      - 'feature/*'
      - 'fix/*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'feature/*'
      - 'fix/*'
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Pre-Release Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/webbanditten/keplercms:prerelease-${{ github.sha }}
      - name: Create Image Tag Comment
        if: ${{ success() }}
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (context.eventName !== 'pull_request') {
              console.log('Not a pull request event');
              return;
            }
            const prNumber = context.payload.pull_request.number;
            const imageTag = 'prerelease-' + '${{ github.sha }}';
            const commentBody = `The pre-release image tag is: ${imageTag}`;
            const octokit = require("@octokit/rest")();
            octokit.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: commentBody
            });
